nelmio_api_doc:
    documentation:
        info:
            title: Book
            description: API Book
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
